version: '3'

services:

  applaravel:
    build: .
    container_name: appLaravel
    entrypoint: dockerize -wait tcp://db:3306 -timeout 40s ./.docker/entrypoint.sh
    volumes: 
      - .:/var/www
    networks: 
      - laravalExercice
    depends_on:
      - db
      - redis
    
  nginx:
    build: .docker/nginx
    container_name: nginxServer
    restart: always
    tty: true
    ports: 
      - "8080:80"
    volumes: 
      - .:/var/www
    networks: 
      - laravalExercice
    depends_on: 
      - applaravel

  redis:
    image: redis:alpine
    container_name: redisServer
    expose:
      - 6379
    networks: 
      - laravalExercice

  db:
    build: .docker/mysql
    command: --innodb-use-native-aio=0
    container_name: dbServer
    restart: always
    tty: true
    ports: 
      - "3306:3306"
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks: 
      - laravalExercice
    healthcheck:
      test: ["CMD-SHELL",'mysql -uroot --database=laravel --password=root --execute="SELECT count(table_name) > 0 FROM information_schema.tables;" --skip-column-names -B']
      interval: 10s
      timeout: 10s
      retries: 4

networks: 
  laravalExercice:
    driver: bridge
